using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Eulers.EulerTwo
{
    class EulerTwoSolution
    {
        public EulerTwoSolution()
        {
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:");
            Console.WriteLine("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
            Console.WriteLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms");

            FibonacciSequence Solution = new FibonacciSequence();
            Solution.CreateSequence(4000000);
            EvenFibonacci SolutionPart2 = new EvenFibonacci(Solution);
            SolutionPart2.SumOfList(SolutionPart2);
        }
    }
}
